### ISSUE TITLE
.desktop not working after flatpak update

### ISSUE THREAD

**Issue by yandiro** [flathub/rest.insomnia.Insomnia#12]
I use it in a flatpak and after  `flatpak update` the gnome shortcut to insomnia does not work anymore, so I have to run it via `flatpak run rest.insomnia.Insomnia` and leave the Terminal open.

I also disabled the packagekit, but I don't think that it would mess it like this.

Results of `latpak info rest.insomnia.Insomnia`

```
Insomnia - Open Source API Client and Design Platform for GraphQL, REST and gRPC.
ID: rest.insomnia.Insomnia
Ref: app/rest.insomnia.Insomnia/x86_64/stable
Arch: x86_64
Branch: stable
Version: 2021.5.3
License: MIT
Origin: flathub
Collection: org.flathub.Stable
Installation: system
Installed: 306.6 MB
Runtime: org.freedesktop.Platform/x86_64/21.08
Sdk: org.freedesktop.Sdk/x86_64/21.08
Commit: 7cc157568f9593cb3e1ed37d4f9724db0db792fd48cbfca9d5ae5b46047f2b9d
Parent: 694d91213bf9add87455ce200d21ad76e51254b349c5a2ac06936eb1553f80e7
Subject: Use AppImage as an upstream source (b901f543)
Date: 2021-09-27 17:45:11 +0000
```

**Comment by Zalaxx** [comment]
Same issue here. Can run Insomnia without issue when launched from the terminal, but it doesn't start with the shortcut. `flatpak info rest.insomnia.Insomnia` returns the same result as above (only difference, `Installation: user` instead of system).

**Comment by WhyNotHugo** [comment]
Sorry, I've been a bit swamped lately and haven't had a look yet.

There's likely something wrong with the desktop file, I'll try and inspect it in the coming week.

In the meantime, please use this as a workaround:

    flatpak run rest.insomnia.Insomnia
