### ISSUE TITLE
I am not able to import collections from a file

### ISSUE THREAD

**Issue by GabrielAyala** [flathub/rest.insomnia.Insomnia#19]
I'm trying to import a collection from a file but Insomnia can't access any folder and consequently I can't import the collection using the file.

![Screenshot from 2021-12-16 13-27-06](https://user-images.githubusercontent.com/51069984/146410196-6374a565-d1e8-4e14-9614-3ca5bcc3ca81.png)

**Comment by WhyNotHugo** [comment]
This can be fixed by Insomnia upgrading to electron 15 or later.

In the meantime, you can use Flatseal to grant permissions to additional directories.

**Comment by GabrielAyala** [comment]
I will try to do this, thanks for answering

**Comment by fabiancrx** [comment]
@WhyNotHugo , this issue could be closed

**Comment by filfreire** [comment]
Hi folks, fyi, this might also be related to what @tqwewe [reported on the Insomnia issues recently](https://github.com/Kong/insomnia/issues/4803#issuecomment-1132641876).

> It seems like the flatpak exec command should include the additional argument `--filesystem=home`.
> 
> A temporary workaround is to edit the file at `/var/lib/flatpak/exports/share/applications/rest.insomnia.Insomnia.desktop` and add the argument to the `Exec` section.
> 
> ```
> sudo nano /var/lib/flatpak/exports/share/applications/rest.insomnia.Insomnia.desktop
> ```
> ```
> [Desktop Entry]
> Name=Insomnia
> Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --filesystem=home --command=/app/bin/insomnia --file-forwarding rest.insomnia.Insomnia --no-sandbox @@u %U @@
> ...
> ```
> Note I added the `--filesystem=home` argument to the entry file.
> 
> Once updated, you can press ALT F2, and enter "r" to reload gnome.

**Comment by WhyNotHugo** [comment]
Editing the desktop file is a bad idea; it'll be overwritten on the next update. Generally, editing package-provided files is a great way for breakage.

The right approach is to configure a local override, and give Insomnia permissions to access the directory where you keep your insomnia files.

- Use [`flatpak-override(1)`](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-override) if you're comfortable with command line.
- Use [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) if you want a GUI.

> It seems like the flatpak exec command should include the additional argument --filesystem=home.

Be warned that this grants Insomnia access to your entire filesystem. It pretty much negates the point of a sandbox entirely; Insomnia can read **any** files, and slip in the right files to highjack your session entirely. Some Flatpak applications do this, and they sacrifice security for the sake of convenience. This will be fixed definitely once Electron uses the FileChooser portal, and Insomnia updates to a compatible Electron version.

**Comment by WhyNotHugo** [comment]
Closing, but pinning since this will be a recurring question.
