### ISSUE TITLE
Any chance of arm64?

### ISSUE THREAD

**Issue by cheywood** [flathub/rest.insomnia.Insomnia#23]
Thanks for the work on the flatpak!

I see it the build was locked down to x86_64 a little way back. Is there any possibility of an arm64 build?

**Comment by WhyNotHugo** [comment]
This package currently uses upstream binaries, and upstream only provides amd64 binaries. There's two ways to get arm64 support here:

- Nag upstream about providing amd64 binaries.
- Rewrite this flatpak to build from source (this sounds like the cleanest approach).

**Comment by hofmmaxi** [comment]
If nobody minds, I would like to take this one over and let the flatpack build from source.
In the process I could also try to add arm64 support.

**Comment by WhyNotHugo** [comment]
Feel free to give it a shot. It would definitely be ideal to build from source.

**Comment by hofmmaxi** [comment]
But I'll probably have to for [this issue](https://github.com/flatpak/flatpak-builder-tools/issues/366) to be fixed before I can continue working on it.
