### ISSUE TITLE
Native wayland support

### ISSUE THREAD

**Issue by miguel-furtado** [flathub/rest.insomnia.Insomnia#25]
Upstream seems to support running in native wayland since the following works:
```
flatpak run rest.insomnia.Insomnia --enable-features=UseOzonePlatform --ozone-platform=wayland
```
It makes a huge difference when using fractional scaling since the fonts will look blurry with xwayland.
Any chance the manifest could include those flags in the command?

**Comment by WhyNotHugo** [comment]
Perhaps https://github.com/flathub/rest.insomnia.Insomnia/pull/2 can be revived for the current version?

Insomnia segfaulted right away last I tried, but it's been a few months.
