### ISSUE TITLE
Flathub is not up-to-date

### ISSUE THREAD

**Issue by mieseprem** [flathub/rest.insomnia.Insomnia#30]
Hello,

I'm not sure who is responsible for the Insomnia Flathub Package, but in case that is 'you': is there a reasons for the Version missmatch Flathub 2022.4.2 vs. Github 2022.6.0?

2022.6.0 was introduced with https://github.com/flathub/rest.insomnia.Insomnia/commit/6b00502be018de8410f73c4d95bf30173f5f023d but that was already 16 days ago.

Overall: thanks for your work!

**Comment by WhyNotHugo** [comment]
This should be pushed automatically by the flathub bot... Looks like something's gone wrong.

Apparently, CI has failed for that last commit: https://buildbot.flathub.org/#/builders/37/builds/390

**Comment by mieseprem** [comment]
Meanwhile it was updated to 2022.7.0
