### ISSUE TITLE
Update to 2023.2.2

### ISSUE THREAD

**Issue by Krisseck** [flathub/rest.insomnia.Insomnia#43]
The latest version is 2023.2.2 https://github.com/Kong/insomnia/releases/tag/core%402023.2.2

Currently it's still on version 2023.1.0 in Flathub

**Comment by azzamsa** [comment]
any update on this?

**Comment by tomaswarynyca** [comment]
@barthalion @WhyNotHugo can you help with this?

**Comment by tomaswarynyca** [comment]
> There's no point in pinging me unless you tested some specific PR and would like me to merge it. If you want to pick up the maintenance of the package, I'm happy to give you access.

Don't take this the wrong way, the flathub bot had created several PRs.
I just made the mention to the repository maintainers to check if it is possible to join those PRs.
If you give me access I would be happy to test the PRs and join if everything works OK.

**Comment by hfiguiere** [comment]
current version is more recent.
