### ISSUE TITLE
Linux version won't show file browse dialog when trying to test a file upload

### ISSUE THREAD

**Issue by bvanhorn-clear** [flathub/rest.insomnia.Insomnia#62]
Two developers on my team are reporting that the version we got from the app store on pop_os 22, which is 2023.5.7, won't display a file dialog box when we want to specify a file on a multipart form POST request.
![insomnia-file-choose](https://github.com/flathub/rest.insomnia.Insomnia/assets/63415326/83493fbf-4782-4fee-b058-788461ebf645)

We click it and nothing happens.  I'd expect the file open dialog box allowing me to navigate and select a file.
It worked in the last version.

**Comment by 4c0n** [comment]
I can confirm that this used to work and doesn't anymore.

**Comment by StoneToken** [comment]
This also fails when trying to open proto files with grpc request.

Version: Insomnia 2023.5.8
Build date: 9/7/2023
OS: Linux x64 6.5.7-200.fc38.x86_64
Electron: 25.2.0
Node: 18.15.0
Node ABI: 116
V8: 11.4.183.23-electron.0
Architecture: x64
Fedora 38 \ Wayland

**Error**
окт 18 14:24:10 stonetoken rest.insomnia.Insomnia.desktop[59500]: (insomnia:2): Gtk-WARNING **: 14:24:10.437: Can't open portal file chooser: GDBus.Error:org.freedesktop.portal.Error.InvalidArgument: invalid filter: name is empty

**Comment by hexchain** [comment]
Please open a new issue if it still happens with the latest version.
