### ISSUE TITLE
Blurry in Wayland

### ISSUE THREAD

**Issue by MrWelsch** [flathub/rest.insomnia.Insomnia#93]
Hello, when using the flatpak version of Insomnia in Gnome 46 under Endeavour OS, the window (I assume it's still gtk3) is very blurry.

![image](https://github.com/user-attachments/assets/ae28f14b-76e2-40e5-8ba5-3f298783fa25)

When trying to fall back to X11 in Flatseal and disabling the wayland windowing system, Insomnia won't start.

I'm using a 3840x2160 resolution, thus making this issue very noticable.

**Comment by hexchain** [comment]
Hmm, I'm also using Insomnia with a 200% scale (under KDE Plasma though), and did not notice any blurry.

Also, to make it run under X11, you'll need to use `--socket=x11 --nosocket=wayland --env=XDG_SESSION_TYPE=x11` (or equivalent overrides).

**Comment by MrWelsch** [comment]
Hi, thank you for the reply.
My Gnome DE is also scaled to 200%.

I have those flags set via flatseal:

![image](https://github.com/user-attachments/assets/967865f3-7fa6-4ee9-8ebf-525b5cd30d74)

**Comment by hexchain** [comment]
You probably also need to add an environment variable override to kick it into X11 mode: `XDG_SESSION_TYPE=x11`.

**Comment by MrWelsch** [comment]
> XDG_SESSION_TYPE=x11

Thank you. That solved my issue.
